### ISSUE TITLE
Animal comments to allow replies

### ISSUE THREAD

**Issue by electric-al** [caim-org/caim-app#2]
## Intro

Currently comments on animals are linear, where each user can only append a new comment.

![Image](https://user-images.githubusercontent.com/149461/192086453-4ec35173-2cc6-4e74-b69d-8072e3c9a743.png)

We would like to support 'nested replies', e.g. the user has the option to reply to an existing comment OR place a new comment.

For now, the max nesting depth is 1, e.g. replies cant have replies.

An example would be something like: 
![image](https://478023200-files.gitbook.io/~/files/v0/b/gitbook-legacy-files/o/assets%2F-LbzMeM9XfnblRd78nga%2F-MW2Nu5J_B1EsyCFPRA7%2F-MW2cOIxr2OqJuRmlfKq%2Fimage.png?alt=media&token=946fedeb-49e0-45fc-b364-e853d42ba128)

(ignore the like / dislike, we MAY do that as a later iteration but its not part of this task)

## UX experience

1. Standard comments as they are now
![Image](https://user-images.githubusercontent.com/149461/192087298-be3a1bcc-040e-4b70-8830-5f48d18e5e55.png)

2. Comments with replies nested. Note that the padding is increased to the left, so that they appear under the parent comment.
![Image](https://user-images.githubusercontent.com/149461/192087300-144838ca-8c13-4209-ac51-1c52a0e5f413.png)

3. If you click 'reply' the reply form appears in the same reply list. Clicking 'reply' submits the comment and the page reloads.
![Image](https://user-images.githubusercontent.com/149461/192087299-1490578a-be4c-4cd7-a667-6a502a7c49e9.png)

## Suggested technical approach

There is an `AnimalComment` object (https://github.com/caim-org/caim-app/blob/main/caim_base/models.py#L350). You could add a 'parent comment' field that is nullable. In the case that a row has parent = NULL it is a top level comment, if its not NULL its under that other comment. The advantage of this method is that in the future we COULD allow more nesting levels.

You would also need to edit the animal comments template here (https://github.com/caim-org/caim-app/blob/main/caim_base/templates/animal/comments.html) to render them correctly.

You could also create a new model for 'AnimalCommentReplies' but this would probably be more work IMO.

## Things to think about

- What happens if someone deletes a comment with replies?

**Comment by izudada** [comment]
Built something on this. Inorder not to make the interface too complicated, I made the replies linear. Kindly test as I await your review of my pull request.

**Comment by electric-al** [comment]
Thanks @izudada merged!
